-- return {
--   "yetone/avante.nvim",
--   event = "VeryLazy",
--   lazy = false,
--   version = false, -- set this to "*" if you want to always pull the latest change, false to update on release
--   opts = {
--     provider = "openai",
--     openai = {
--       model = "gpt-4o-mini",
--       timeout = 30000, -- Timeout in milliseconds
--       temperature = 0,
--     },
--     -- add any opts here
--   },
--   -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
--   build = "make",
--   -- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
--   dependencies = {
--     "stevearc/dressing.nvim",
--     "nvim-lua/plenary.nvim",
--     "MunifTanjim/nui.nvim",
--     --- The below dependencies are optional,
--     "hrsh7th/nvim-cmp", -- autocompletion for avante commands and mentions
--     "nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
--     {
--       -- Make sure to set this up properly if you have lazy=true
--       "MeanderingProgrammer/render-markdown.nvim",
--       opts = {
--         file_types = { "markdown", "Avante" },
--         provider = "claude",
--       },
--       ft = { "markdown", "Avante" },
--     },
--   },
-- }
